### ISSUE TITLE
Hud in bottom left doesn't working higher res monitors

### ISSUE THREAD

**Issue by DavidAGullo** [qbcore-fivem/qb-hud#18]
anything higher than 1920x1080 moves the icons off the circles

**Comment by GhzGarage** [comment]
This has been tested already. Please show a screenshot.

**Comment by codygulley** [comment]
I have noticed this as well. The icons all shift due to the CSS stylings using pixel offsets rather than percentages or other calculated units. Any resolution that has a width other than 1920 has issues. Anything greater icons are offset to the right, anything less and icons are set to the left. 

@GhzGarage  Here is are a set of examples with Advanced Graphics -> Resolution set to different resolutions.

3620 x 2036 :
![qb-hud-3620by2036](https://user-images.githubusercontent.com/8097956/131249099-be32bbea-af3b-4764-b9d1-a50007f36e58.PNG)

1920 x 1080:
![qb-hud-1920by1080](https://user-images.githubusercontent.com/8097956/131249122-2f3d5d3f-342c-47b5-86e9-ef3adc2d2e61.PNG)

1768 x 992:
![qb-hud-1768by992](https://user-images.githubusercontent.com/8097956/131249189-f53722fd-bfe9-449f-b7e0-a790765823c5.PNG)

**Comment by DavidAGullo** [comment]
Thank you @codygulley It wasn't on my computer I have a normal 1080 monitor,

**Comment by codygulley** [comment]
My apologies this doesn't look to be of issue any more. I didn't notice that my code was a couple commits behind.  @DavidAGullo  can you get the latest code and verify you're not experiencing this any more?

**Comment by GhzGarage** [comment]
Yeah the new hud update should fix that
